version: '3'

services:
  tesseract:
    image: ocr-tesseract-docker:latest
    container_name: tesseract
    tty: true
    volumes:
      - ./data:/var/www/data
      - ./src:/app/src
    ports:
      - 5050:5000
